### ISSUE TITLE
division by 0?

### ISSUE THREAD

**Issue by atelieraterui** [yoreyore/0AJAD04-2020#1]
Asirでプログラムを実行したところ、以下のエラーが出ました。
```
[1893] load("report.rr");
div : division by 0
return to toplevel
[1906] 
```
一応確認してもらえればと思います。
動作環境は学情の ubuntu.u.tsukuba.ac.jp の Asir です。
レポートの成績には影響しませんのでご安心ください（計算機代数はA+相当です）。

**Comment by yoreyore** [comment]
ご指摘ありがとうございます。
レポートの作成環境は Asir の Version 20191120 で、こちらではエラーなく実行できました。
学情の ubuntu.u.tsukuba.ac.jp で試し、同様のエラーが確認できたため、原因を探したところ、77行目のbreak文と79行目のcontinue文が実行できていないと思われる挙動が確認できました。
continue文によるスキップが起こらないため、81行目の対角成分で行を割る操作を対角成分が0の場合にも行ってしまい、エラーが発生したようです。
学情の Asir は Version 20151202 なので、バージョン差かもしれません (レポートにバージョンも載せるべきでした)。

**Comment by atelieraterui** [comment]
なるほどわかりました。確認ありがとうございます。
自分の手元の mac の asir 20191011 では正常に実行できました。
学情の asir は、今の全学計算機の導入時に入ったバージョンかもしれません。
asir のデバッガを使いたかったのですが、ファイルのloadと関数定義まで終わらないとデバッグができないので、できればBerlekamp全体の計算を1つの関数で def してもらえると、デバッグがしやすくなると思います。ご検討ください。
新しい asir では正常に実行できますし、そういう意味では正しいプログラムだと思いますので、一応この issue は close しておきます。
