### ISSUE TITLE
レポートのスクリーンショットの画像ファイルがない

### ISSUE THREAD

**Issue by atelieraterui** [yoreyore/0AJAD04-2020#2]
ついでで恐縮ですが、レポート本体のスクリーンショットのpngファイルがリポジトリに上がっていないので、texソースがあってもpdfの完全な生成には至りませんね...。

**Comment by yoreyore** [comment]
申し訳ございません。画像ファイルを追加いたしました。
また、バールカンプアルゴリズム全体が一つの関数となるように report.rr を書き直しました。

**Comment by atelieraterui** [comment]
ありがとうございます。ファイルの追加は確認しました。
report.rr の修正の方はまた時間がある時に確認したいと思います。
ひとまず issue を閉じます。
